# Site
repository: christianzhou1/christianzhou1.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Christian Zhou
title: McMaster Computer Science Co-op
email: zhouz229 at mcmaster dot ca
# email_title: Email (Email title override)
# phone: 
# phone_title: Phone (Phone title override)
# website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  christianzhou1
linkedin_username: christian-zhou

# Additional icon links
# additional_links:
# - title: The Todo Project
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  # url: https://todo.christianzhou.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: |
  I'm Christian Zhou, a Computer Science student passionate about software engineering, cloud deployment, and intelligent systems. I focus on building practical, scalable solutions that bridge backend efficiency with intuitive frontend design.

  My work spans full-stack web applications using **Spring Boot**, **React**, and **PostgreSQL**, as well as **machine learning** and **data visualization** projects. I enjoy designing systems that automate workflows, analyze data, and improve user experience.

  Outside coursework, I explore **DevOps**, **AWS**, and **AI-driven knowledge tools**. I value clear architecture, reproducibility, and well-documented code.

  - Core Skills: Java, Python, TypeScript, SQL, Docker  
  - Interests: Cloud infrastructure, data pipelines, data analysis, and applied ML  
  - [GitHub](https://github.com/christian-zhou) · [LinkedIn](https://linkedin.com/in/christian-zhou)


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: The Todo Project
        link: https://todo.christianzhou.com/
        link_text: https://todo.christianzhou.com/
        additional_links:
          - title:  GitHub
            icon: fab fa-github
            url: https://github.com/christianzhou1/the-todo-project
        quote: >
          Full-stack project inspired by production backend systems maintained during my co-op term.
        description: |
          **The Todo Project** is a **full-stack task management system** built with a **Spring Boot + PostgreSQL** backend and a **React + TypeScript** frontend, inspired by enterprise-grade architecture from my co-op experience.

          **Key Features**
          - **RESTful APIs** with **JWT authentication** and **role-based access control**
          - **File attachments** stored via **AWS S3**, integrated with OpenAPI-generated TypeScript clients for type-safe frontend communication  
          - **Containerized deployment** using **Docker Compose**, orchestrating backend, frontend, and database services  
          - **Nginx reverse proxy** with **HTTPS (Certbot)** and **automated deployment scripts** written in Bash and PowerShell

          **Focus Areas**
          - Production-aligned architecture emphasizing **service-layer separation**, **DTO mapping**, and **Flyway migrations**
          - Scalable **PostgreSQL schema design** for multi-user and task-attachment relations  
          - Maintainable **CI/CD-style workflow** mirroring real-world DevOps practices
  - title: Experience
    layout: list
    content:
      - layout: right
        title: IDI-Itech Development Inc.
        sub_title: Website Developer
        caption: September 2025 - December 2025
        # link: Link to company (optional)
        # quote: >
          # Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          • Maintained and enhanced the IT team’s Java Spring Boot backend repository, resolving bugs, improving service-layer documentation, and managing code changes with Git version control.
          
          • Led WordPress malware remediation on SiteGround; removed PHP backdoors, purged ∼6,000 spam posts, implemented Apache protections, and achieved a clean Sucuri scan; consolidated domain/DNS records and automated billing extraction using Python regex.
          
          • Self-Developed Project: Built a production-aligned application modeled after the company’s backend using Spring Boot, PostgreSQL, and React (Vite); implemented JWT authentication, AWS S3 integration, and OpenAPI-generated TypeScript clients.
          
          • Containerized and deployed all services on a DigitalOcean VPS using Docker Compose and Nginx; automated deployment via Bash & PowerShell scripts; secured server with Ubuntu firewall & HTTPS.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: McMaster University
        sub_title: BASc, Computer Science Co-op
        caption: 2022-2027
        # quote: >
          # Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
          # Description of qualification
  - title: Skills
    layout: text
    content: |
      **Programming Languages:** Python, Java, TypeScript, JavaScript, SQL, C++, Go  
      **Frameworks & Libraries:** Spring Boot, React, Node.js, Express, Flask, Tailwind CSS  
      **Databases:** PostgreSQL, MySQL, DynamoDB, MongoDB  
      **DevOps & Tools:** Docker, GitHub Actions, AWS (EC2, S3, RDS), Vercel, Flyway, Nginx  
      **Machine Learning:** scikit-learn, NumPy, pandas, Matplotlib  
      **Other Skills:** API design, system architecture, cloud deployment, test automation, data visualization

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
